name: Test
on: push

jobs:
  lint-lib:
    name: Lint the library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn lib:lint
  lint-app:
    name: Lint the app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn app:lint
