name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            always-auth: true
        - uses: bahmutov/npm-install@v1
        - name: copy readme
          run: cp README.md projects/rohmer/ng-portal
        - name: build lib
          run: yarn lib:build
        - name: publish
          run: yarn publish --new-version ${GITHUB_REF/refs\/tags\//} --no-git-tag-version
          working-directory: ./dist/rohmer/ng-portal
          env:
            NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
